name: Deploy

on:
  pull_request:
    branches:
    - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: publish lambda function
        id: publish_lambda_function
        run: |
          echo "start pubish"
          zip -j deploy.zip lambda_function.py
          aws lambda update-function-code --function-name=process_s3_data_function --zip-file=fileb://deploy.zip
          aws lambda update-function-configuration --function-name process_s3_data_function  --environment 'Variables={env=prod}'
          aws publish-version --function-name process_s3_data_function 2>&1 | tee test.log
          cat test.log